#!/usr/bin/env python3
"""
Development-only reference tooling for ColorAdapt M2 (Color Vision Simulation).

NOT part of the extension. No runtime dependency is added to the product.

What it does
------------
1. Downloads Table 1 of Machado, Oliveira & Fernandes (2009) from the authors'
   page, parses it, cross-checks it against the independent copy shipped in
   DaltonLens-Python, and writes `src/core/vision/machado2009-data.ts`.
2. Uses DaltonLens-Python (https://github.com/DaltonLens/DaltonLens-Python,
   Nicolas Burrus) as an *independent* implementation of Brettel 1997,
   Vienot 1999 and Machado 2009 to compute expected values for a curated set
   of colors, and writes `tests/fixtures/vision/reference-vectors.json`.

IMPORTANT: use DaltonLens-Python commit 3cba5e6 (or newer), NOT the PyPI 0.1.5
release. 0.1.5 feeds Smith & Pokorny cone fundamentals with plain CIE 1931 XYZ,
whereas that matrix is defined for Judd-Vos corrected XYZ (as in Vienot 1999).
The fixed implementation is what libDaltonLens ships.

KNOWN REFERENCE BUG: Simulator_Machado2009 in DaltonLens-Python interpolates
between tabulated matrices with weight `severity - floor(severity*10)/10`
(range 0..0.1) instead of `*10` (range 0..1; the authors' own example uses
weight 0.73 for severity 0.873). Machado vectors are therefore generated only
at tabulated severities; ColorAdapt's interpolation is tested against a
hand-computed expectation instead.

Usage
-----
    python -m venv .venv && .venv/bin/pip install numpy \n      https://github.com/DaltonLens/DaltonLens-Python/archive/3cba5e6a7c8f0e8199c8f83f1afb58eb6dab7a3d.zip
    .venv/bin/python scripts/reference/generate_reference.py

The fixture is committed, so normal development and CI never need Python.
"""
import json
import re
import sys
import urllib.request
from importlib.metadata import version
from pathlib import Path

import numpy as np
from daltonlens import simulate, convert

ROOT = Path(__file__).resolve().parents[2]
MACHADO_URL = (
    "https://www.inf.ufrgs.br/~oliveira/pubs_files/CVD_Simulation/CVD_Simulation.html"
)
FAMILIES = {
    "protan": simulate.Deficiency.PROTAN,
    "deutan": simulate.Deficiency.DEUTAN,
    "tritan": simulate.Deficiency.TRITAN,
}

# Curated colors (8-bit sRGB): required primaries/secondaries/neutrals plus mixed colors.
COLORS = {
    "black": (0, 0, 0),
    "white": (255, 255, 255),
    "red": (255, 0, 0),
    "green": (0, 255, 0),
    "blue": (0, 0, 255),
    "cyan": (0, 255, 255),
    "magenta": (255, 0, 255),
    "yellow": (255, 255, 0),
    "gray-128": (128, 128, 128),
    "gray-119": (119, 119, 119),
    "orange": (255, 165, 0),
    "steel-blue-336699": (51, 102, 153),
    "coral-ff6b6b": (255, 107, 107),
    "emerald-2ecc71": (46, 204, 113),
    "purple-8e44ad": (142, 68, 173),
    "sunflower-f1c40f": (241, 196, 15),
    "turquoise-1abc9c": (26, 188, 156),
    "alizarin-e74c3c": (231, 76, 60),
    "wet-asphalt-34495e": (52, 73, 94),
    "silver-bdc3c7": (189, 195, 199),
    "olive-808000": (128, 128, 0),
    "dark-red-8b0000": (139, 0, 0),
}


def parse_machado_table(html: str):
    """Return {family: [11 x (9-tuple row-major)]} parsed from Table 1."""
    nums = [float(m) for m in re.findall(r"<td[^>]*>\s*([-+]?\d+\.\d{6})\s*</td>", html)]
    assert len(nums) == 297, len(nums)
    out = {"protan": [], "deutan": [], "tritan": []}
    i = 0
    for _sev in range(11):
        for fam in ("protan", "deutan", "tritan"):
            out[fam].append(tuple(nums[i : i + 9]))
            i += 9
    return out


def crosscheck_with_daltonlens(table):
    worst = 0.0
    for fam, d in FAMILIES.items():
        for k in range(11):
            ref = np.array(simulate.machado_2009_matrices[d][k]).reshape(9)
            worst = max(worst, float(np.max(np.abs(ref - np.array(table[fam][k])))))
    print(f"Machado table vs DaltonLens-Python table: max |delta| = {worst:.2e}")
    assert worst < 1e-6, "Parsed Machado table disagrees with DaltonLens copy"


def write_machado_ts(table):
    fmt = lambda m: "[" + ", ".join(f"{v:.6f}".replace("-0.000000", "0.000000") for v in m) + "]"
    lines = [
        "// GENERATED by scripts/reference/generate_reference.py - do not edit by hand.",
        "//",
        "// Source: Machado, Oliveira & Fernandes (2009), Table 1 (\"Simulation matrices\"),",
        f"// {MACHADO_URL}",
        "// Cross-checked against the table shipped in DaltonLens-Python "
        f"{version('daltonlens')} (max abs delta < 1e-6).",
        "// Row-major 3x3 matrices, severity 0.0..1.0 in steps of 0.1, applied to LINEAR RGB.",
        "",
        "export type Mat3Tuple = readonly [number, number, number, number, number, number, number, number, number];",
        "",
        "export const MACHADO_2009_SEVERITY_STEPS = 10;",
        "",
        "export const MACHADO_2009_MATRICES: Readonly<",
        "  Record<'protan' | 'deutan' | 'tritan', readonly Mat3Tuple[]>",
        "> = {",
    ]
    for fam in ("protan", "deutan", "tritan"):
        lines.append(f"  {fam}: [")
        for m in table[fam]:
            lines.append(f"    {fmt(m)},")
        lines.append("  ],")
    lines.append("};")
    (ROOT / "src/core/vision/machado2009-data.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")


def srgb_from_linear(v):
    v = np.clip(v, 0.0, 1.0)
    return np.where(v < 0.0031308, v * 12.92, np.power(v, 1 / 2.4) * 1.055 - 0.055)


def main():
    html = urllib.request.urlopen(MACHADO_URL).read().decode("utf-8", "replace")
    table = parse_machado_table(html)
    assert convert.LMSModel_sRGB_SmithPokorny75().usesJuddVosXYZ, "need DaltonLens-Python >= 3cba5e6"
    crosscheck_with_daltonlens(table)
    write_machado_ts(table)

    srgb8 = np.array(list(COLORS.values()), dtype=np.uint8).reshape(1, -1, 3)
    linear_in = convert.linearRGB_from_sRGB(convert.as_float32(srgb8).astype(np.float64))

    sims = {
        "brettel1997": (simulate.Simulator_Brettel1997(), ["protan", "deutan", "tritan"], [1.0, 0.5]),
        "vienot1999": (simulate.Simulator_Vienot1999(), ["protan", "deutan"], [1.0, 0.5]),
        "machado2009": (simulate.Simulator_Machado2009(), ["protan", "deutan", "tritan"], [0.0, 0.3, 0.5, 1.0]),  # tabulated steps only, see note below
    }
    cases = []
    for model, (sim, fams, severities) in sims.items():
        for fam in fams:
            for sev in severities:
                d = FAMILIES[fam]
                lin_out = sim._simulate_cvd_linear_rgb(linear_in, d, sev)[0]
                srgb_float = srgb_from_linear(lin_out)
                public8 = sim.simulate_cvd(srgb8, d, sev)[0]
                cases.append(
                    {
                        "model": model,
                        "family": fam,
                        "severity": sev,
                        "results": [
                            {
                                "color": name,
                                "input": list(rgb),
                                "linearOut": [float(x) for x in lin_out[i]],
                                "srgbOut": [float(x) for x in srgb_float[i]],
                                "srgb8Out": [int(x) for x in public8[i]],
                            }
                            for i, (name, rgb) in enumerate(COLORS.items())
                        ],
                    }
                )
    doc = {
        "provenance": {
            "tool": "scripts/reference/generate_reference.py",
            "referenceImplementation": f"DaltonLens-Python {version('daltonlens')} @ 3cba5e6 (numpy {version('numpy')})",
            "referenceCommit": "3cba5e6a7c8f0e8199c8f83f1afb58eb6dab7a3d",
            "independentCrossChecks": [
                "libDaltonLens.c Brettel/Viénot protan constants (plane1/plane2/separation normal, Viénot matrix) agree with ColorAdapt derivation to 5 decimals (M2.R1)",
                "Machado 2009 Table 1 parsed from the authors' page equals the DaltonLens-Python table (< 1e-6)",
            ],
            "tolerances": {
                "matrixConstants": 2e-5,
                "linearRgbAndFloatSrgb": 1e-6,
                "srgb8Bit": "within 1 level",
            },
            "assumptions": [
                "Machado 2009 matrices are applied to LINEAR RGB (ENGINEERING CONVENTION, M2.R1 primary review = category D: neither the paper nor the authors' page states the encoding and no official code exists; Eqs. 8-10 derive the matrices by integrating RGB-primary spectral power distributions, which implies linear-light RGB but is not an explicit statement)",
                "Machado vectors only at tabulated severities (reference interpolation is buggy)",
            ],
            "notes": [
                "linearOut: unclamped linear-RGB output of the reference simulator (float64).",
                "srgbOut: clamp to [0,1] and sRGB-encode the above in float (reference formula).",
                "srgb8Out: DaltonLens public simulate_cvd() 8-bit output (float32 pipeline), for +-1 level cross-check.",
                "Inputs are 8-bit sRGB values divided by 255.",
            ],
        },
        "cases": cases,
    }
    out = ROOT / "tests/fixtures/vision/reference-vectors.json"
    out.write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(cases)} cases x {len(COLORS)} colors)")


if __name__ == "__main__":
    sys.exit(main())
