import { describe, expect, it } from 'vitest';
import { mat3Mul, mat3MulVec } from '@core/color';
import {
  LINEAR_RGB_FROM_LMS,
  LMS_FROM_LINEAR_RGB,
  brettelDichromacy,
  brettelParams,
  vienotMatrix,
} from '@core/vision';

function expectMatClose(actual: readonly number[], expected: readonly number[], tol: number): void {
  expect(actual).toHaveLength(expected.length);
  expected.forEach((e, i) => expect(Math.abs(actual[i]! - e)).toBeLessThanOrEqual(tol));
}

/**
 * Expected values below are NOT produced by this code base. They were taken
 * from libDaltonLens (Nicolas Burrus, public domain), `libDaltonLens.c`, whose
 * constants were generated by DaltonLens-Python from the same published
 * models (Smith & Pokorny 1975 cone fundamentals with sRGB primaries;
 * Brettel et al. 1997 anchors 475/575 nm and 485/660 nm; Viénot et al. 1999
 * blue/yellow plane), rounded to 5 decimals. Tolerance 2e-5 covers that rounding
 * and is far below the ~1e-2 error any wrong anchor or LMS matrix would cause.
 */
const TOL = 2e-5;

describe('LMS model (Smith & Pokorny 1975 on Judd-Vos XYZ, sRGB primaries)', () => {
  it('matches DaltonLens-Python LMSModel_sRGB_SmithPokorny75.LMS_from_linearRGB', () => {
    // Also equals the widely used "17.8824 43.5161 4.11935 ..." matrix divided by 100.
    expectMatClose(
      LMS_FROM_LINEAR_RGB,
      [
        0.178824041258, 0.4351609057, 0.04119349692, 0.034556423182, 0.27155382458, 0.03867130836,
        0.000299565576, 0.0018430896, 0.01467086136,
      ],
      1e-9,
    );
  });

  it('has an exact inverse', () => {
    const p = mat3Mul(LMS_FROM_LINEAR_RGB, LINEAR_RGB_FROM_LMS);
    expectMatClose(p, [1, 0, 0, 0, 1, 0, 0, 0, 1], 1e-9);
  });
});

describe('Brettel 1997 derived parameters', () => {
  it('protan: two projection planes and separation normal', () => {
    const p = brettelParams('protan');
    expectMatClose(
      p.plane1,
      [0.1498, 1.19548, -0.34528, 0.10764, 0.84864, 0.04372, 0.00384, -0.0054, 1.00156],
      TOL,
    );
    expectMatClose(
      p.plane2,
      [0.1457, 1.16172, -0.30742, 0.10816, 0.85291, 0.03892, 0.00386, -0.00524, 1.00139],
      TOL,
    );
    expectMatClose(p.separationNormalRgb, [0.00048, 0.00393, -0.00441], 1e-5);
  });

  it('deutan: two projection planes and separation normal', () => {
    const p = brettelParams('deutan');
    expectMatClose(
      p.plane1,
      [0.36477, 0.86381, -0.22858, 0.26294, 0.64245, 0.09462, -0.02006, 0.02728, 0.99278],
      TOL,
    );
    expectMatClose(
      p.plane2,
      [0.37298, 0.88166, -0.25464, 0.25954, 0.63506, 0.1054, -0.0198, 0.02784, 0.99196],
      TOL,
    );
    expectMatClose(p.separationNormalRgb, [-0.00281, -0.00611, 0.00892], 1e-5);
  });

  it('tritan: two projection planes (485/660 nm anchors) and separation normal', () => {
    const p = brettelParams('tritan');
    expectMatClose(
      p.plane1,
      [1.01277, 0.13548, -0.14826, -0.01243, 0.86812, 0.14431, 0.07589, 0.805, 0.11911],
      TOL,
    );
    expectMatClose(
      p.plane2,
      [0.93678, 0.18979, -0.12657, 0.06154, 0.81526, 0.1232, -0.37562, 1.12767, 0.24796],
      TOL,
    );
    expectMatClose(p.separationNormalRgb, [0.03901, -0.02788, -0.01113], 1e-5);
  });

  it('is not a single matrix: the two planes differ for every family', () => {
    for (const f of ['protan', 'deutan', 'tritan'] as const) {
      const p = brettelParams(f);
      const maxDiff = Math.max(...p.plane1.map((v, i) => Math.abs(v - p.plane2[i]!)));
      expect(maxDiff).toBeGreaterThan(0.02);
    }
  });

  it('selects each plane according to the side of the separation plane', () => {
    const samples: [number, number, number][] = [
      [1, 0, 0],
      [0, 1, 0],
      [0, 0, 1],
      [1, 1, 0],
      [0, 1, 1],
      [1, 0, 1],
    ];
    for (const f of ['protan', 'deutan', 'tritan'] as const) {
      const p = brettelParams(f);
      const sides = new Set<boolean>();
      for (const c of samples) {
        const positive =
          c[0] * p.separationNormalRgb[0] +
            c[1] * p.separationNormalRgb[1] +
            c[2] * p.separationNormalRgb[2] >=
          0;
        sides.add(positive);
        expectMatClose(
          brettelDichromacy(c, f),
          mat3MulVec(positive ? p.plane1 : p.plane2, c),
          1e-12,
        );
      }
      expect(sides.size).toBe(2); // both half-planes are really used
    }
  });

  it('is a projection: applying it twice changes nothing', () => {
    for (const f of ['protan', 'deutan', 'tritan'] as const) {
      for (const c of [
        [0.8, 0.1, 0.3],
        [0.1, 0.7, 0.2],
        [0.2, 0.3, 0.9],
      ] as const) {
        const once = brettelDichromacy(c, f);
        const twice = brettelDichromacy(once, f);
        expectMatClose(twice, once, 1e-6);
      }
    }
  });

  it('keeps the achromatic axis fixed (white and grays are unchanged)', () => {
    for (const f of ['protan', 'deutan', 'tritan'] as const) {
      expectMatClose(brettelDichromacy([1, 1, 1], f), [1, 1, 1], 1e-4);
      expectMatClose(brettelDichromacy([0.3, 0.3, 0.3], f), [0.3, 0.3, 0.3], 1e-4);
    }
  });
});

describe('Viénot 1999 derived matrices', () => {
  it('protan matches DaltonLens precomputed matrix', () => {
    expectMatClose(
      vienotMatrix('protan'),
      [0.11238, 0.88762, 0, 0.11238, 0.88762, 0, 0.00401, -0.00401, 1],
      TOL,
    );
  });

  it('deutan matches DaltonLens precomputed matrix', () => {
    expectMatClose(
      vienotMatrix('deutan'),
      [0.29275, 0.70725, 0, 0.29275, 0.70725, 0, -0.02234, 0.02234, 1],
      TOL,
    );
  });
});
