import { describe, expect, it } from 'vitest';
import type { ColorValue, VisionModel, VisionProfile } from '@domain/models';
import { createVisionSimulator } from '@core/vision';
import { machadoMatrix } from '@core/vision';
import { MACHADO_2009_MATRICES } from '@core/vision/machado2009-data';
import fixture from '../../fixtures/vision/reference-vectors.json';

/**
 * Cross-validation against an independent implementation.
 *
 * `reference-vectors.json` is generated by scripts/reference/generate_reference.py
 * with DaltonLens-Python (see `provenance` in the file). The expected values are
 * NOT computed by ColorAdapt code. Colors: black, white, primaries,
 * secondaries, grays and mixed colors (22 total).
 *
 * Tolerances:
 *  - linear / float sRGB: 1e-6. The reference converts 8-bit inputs in float32
 *    (~3e-8 relative error) while ColorAdapt uses float64; the remaining slack is
 *    for rounded published constants. A wrong matrix, wrong anchor, wrong plane
 *    choice or a missing sRGB decode shifts results by >1e-3, i.e. 1000x the tolerance.
 *  - 8-bit public API output: +-1 level (float32 truncation vs. rounding).
 */
const TOL = 1e-6;

interface Result {
  color: string;
  input: [number, number, number];
  srgbOut: [number, number, number];
  srgb8Out: [number, number, number];
}
interface Case {
  model: VisionModel;
  family: 'protan' | 'deutan' | 'tritan';
  severity: number;
  results: Result[];
}

// Pick a profile whose family matches, then force the model under test via policy override.
const PROFILE_FOR_FAMILY: Record<Case['family'], VisionProfile> = {
  protan: 'protanopia',
  deutan: 'deuteranopia',
  tritan: 'tritanopia',
};

const cases = fixture.cases as unknown as Case[];

function color(input: [number, number, number]): ColorValue {
  return { r: input[0] / 255, g: input[1] / 255, b: input[2] / 255, alpha: 1 };
}

describe('reference vectors (DaltonLens-Python)', () => {
  it('covers the required curated colors', () => {
    const names = new Set(cases[0]!.results.map((r) => r.color));
    for (const required of [
      'black',
      'white',
      'red',
      'green',
      'blue',
      'cyan',
      'magenta',
      'yellow',
      'gray-128',
    ]) {
      expect(names.has(required)).toBe(true);
    }
    expect(names.size).toBeGreaterThanOrEqual(15);
  });

  it('covers every implemented model and family', () => {
    const keys = new Set(cases.map((c) => `${c.model}:${c.family}`));
    for (const f of ['protan', 'deutan', 'tritan']) {
      expect(keys.has(`brettel1997:${f}`)).toBe(true);
      expect(keys.has(`machado2009:${f}`)).toBe(true);
    }
    expect(keys.has('vienot1999:protan')).toBe(true);
    expect(keys.has('vienot1999:deutan')).toBe(true);
  });

  for (const c of cases) {
    it(`${c.model} ${c.family} severity ${c.severity}`, () => {
      const profile = PROFILE_FOR_FAMILY[c.family];
      const simulator = createVisionSimulator({ [profile]: c.model });
      for (const r of c.results) {
        const out = simulator.simulate(color(r.input), profile, c.severity);
        const actual = [out.r, out.g, out.b];
        r.srgbOut.forEach((expected, i) => {
          const delta = Math.abs(actual[i]! - expected);
          expect(delta, `${r.color} channel ${i}: ${actual[i]} vs ${expected}`).toBeLessThanOrEqual(
            TOL,
          );
        });
        r.srgb8Out.forEach((expected, i) => {
          expect(Math.abs(Math.round(actual[i]! * 255) - expected)).toBeLessThanOrEqual(1);
        });
      }
    });
  }
});

describe('Machado 2009 table', () => {
  it('has 11 severities per family with identity at 0 and rows summing to 1 (white preserved)', () => {
    for (const family of ['protan', 'deutan', 'tritan'] as const) {
      const table = MACHADO_2009_MATRICES[family];
      expect(table).toHaveLength(11);
      expect(Array.from(table[0]!)).toEqual([1, 0, 0, 0, 1, 0, 0, 0, 1]);
      for (const m of table) {
        for (let row = 0; row < 3; row++) {
          expect(m[row * 3]! + m[row * 3 + 1]! + m[row * 3 + 2]!).toBeCloseTo(1, 4);
        }
      }
    }
  });

  it('spot-checks published severity-1.0 entries (Table 1 of the paper)', () => {
    expect(Array.from(MACHADO_2009_MATRICES.protan[10]!)).toEqual([
      0.152286, 1.052583, -0.204868, 0.114503, 0.786281, 0.099216, -0.003882, -0.048116, 1.051998,
    ]);
    expect(Array.from(MACHADO_2009_MATRICES.deutan[10]!)).toEqual([
      0.367322, 0.860646, -0.227968, 0.280085, 0.672501, 0.047413, -0.01182, 0.04294, 0.968881,
    ]);
    expect(Array.from(MACHADO_2009_MATRICES.tritan[10]!)).toEqual([
      1.255528, -0.076749, -0.178779, -0.078411, 0.930809, 0.147602, 0.004733, 0.691367, 0.3039,
    ]);
  });

  it('interpolates linearly between tabulated severities', () => {
    const m = machadoMatrix('protan', 0.35);
    const a = MACHADO_2009_MATRICES.protan[3]!;
    const b = MACHADO_2009_MATRICES.protan[4]!;
    m.forEach((v, i) => expect(v).toBeCloseTo((a[i]! + b[i]!) / 2, 12));
  });

  it('returns the tabulated matrix at exact steps, including severity 1', () => {
    expect(Array.from(machadoMatrix('deutan', 1))).toEqual(
      Array.from(MACHADO_2009_MATRICES.deutan[10]!),
    );
    expect(Array.from(machadoMatrix('deutan', 0.3))).toEqual(
      Array.from(MACHADO_2009_MATRICES.deutan[3]!),
    );
  });
});
